# Generated by Django 2.2.24 on 2022-12-18 07:33

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            full_name=flat.owner,
            pure_phone=flat.owner_pure_phone,
            defaults={
                'full_name': flat.owner,
                'pure_phone': flat.owner_pure_phone,
            },
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221218_0152'),
    ]

    operations = [
        migrations.RunPython(fill_owners, move_backward),
    ]
